### ISSUE TITLE
创建iOS文件显示不支持当前的iSO模板！

### ISSUE THREAD

**Issue by WRMYX** [slorelee/wimbuilder2#100]
前面的安装一切顺利，就是到了创建iso的时候显示当前ISO模板不适用这个时候该怎么办？

**Comment by slorelee** [comment]
模板是从系统ISO镜像复制的，要么就自己准备模板复制到 _ISO_ 目录中。
你应该是只选择了，install.wim文件，没有选挂载的ISO光盘镜像的盘符。
