### ISSUE TITLE
开启UWP后使用PE时并没有相关的应用

### ISSUE THREAD

**Issue by WRMYX** [slorelee/wimbuilder2#101]
开启UWP后使用PE时并没有相关的应用,就比如说任务栏和设置还有任务管理器都没有像windows11的那种样式

**Comment by slorelee** [comment]
报告问题的请说明下，你使用的Windows镜像的版本。
UWP组件目前需要 2263x 以上的版本才可以生效。

**Comment by WRMYX** [comment]
可以把魔改好了的W2制作器发给我嘛？在其他地方找不到制作方法了！求求了！

**Comment by WRMYX** [comment]
我用的镜像是22635.3061

**Comment by WRMYX** [comment]
或是你把一个制作好了的发给我一下！谢谢🙏
