### ISSUE TITLE
可以让我体验一下wimbuilder2的内测版吗?

### ISSUE THREAD

**Issue by WRMYX** [slorelee/wimbuilder2#104]
可以让我体验一下wimbuilder2的内测版吗?

**Comment by slorelee** [comment]
你看截图时间，2023-11-11 技术预览版就是新的。

没有内测版本，关于里面从 Gitee，github 在线更新就行。启动不了就自己更新StartAllBack 3.7.8。

**Comment by slorelee** [comment]
beta版本在release发布了。
