### ISSUE TITLE
WinPE made with 1889x system is not working properly

### ISSUE THREAD

**Issue by TheZihanGu** [slorelee/wimbuilder2#15]
test version: 2019.04.28.8a4aaaea
test windows version:18890 18894 18895 (zh-cn,Windows Pro)
unsuccessful changes:
1. unable to open the start menu.
2. the computer name modification in the PE failed.
3. network driver is not available (with PENetwork)

**Comment by slorelee** [comment]
@TheZihanGu 

> test windows version:18890 18894 18895 (zh-cn,Windows Pro)

Ensure that the response is correct, I will reply with Chinese.

> 1.unable to open the start menu.

我使用18894测试，StartIsBack 2.8.4 的开始菜单功能正常。
请确认X:\Program Files\StartIsBack是否存在。

从github下载的master.zip不包含第3方应用程序。
你如果可以访问下面的链接, 可以下载包含了第3方应用程序的工程包
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=411399&page=61#pid3781022

如果你无法下载，请告知，我将打包放到github的Release页面。

> 2.the computer name modification in the PE failed.

你使用什么命令，工具修改计算机名？
还是说我的电脑属性页面，系统的修改计算名的界面丢失，希望添加？

> 3. network driver is not available (with PENetwork)

暂时此工具没有集成非系统的驱动文件。如果没有你的网卡驱动，
你需要自己准备对应的驱动文件。(inf, sys)
然后进入PE后通过drvload命令加载该驱动。



If you

**Comment by TheZihanGu** [comment]
emm没有无忧账号，能发个release或者提供一个网盘链接么

**Comment by slorelee** [comment]
> emm没有无忧账号，能发个release或者提供一个网盘链接么

https://github.com/slorelee/wimbuilder2/releases/download/v2019.04.29_beta/WimBuilder2.7z

**Comment by KooriMoe** [comment]
由于某些原因，能否请您删除这个 Issue?
十分感谢。
