### ISSUE TITLE
not work in LOG mode

### ISSUE THREAD

**Issue by nonamemanSEO** [slorelee/wimbuilder2#16]
hi~ dear my friend Slore!
it's long time to see you, because i'm very busy with my own business.
I always feel sorry for not giving you the feedback immediately and seeing it away every time.

i downloaded latest version and tried to build, but it didn't work in LOG mode.
in CMD mode, it works.

**Comment by slorelee** [comment]
Hi, @nonamemanSEO 

Yes, It is long time to see you. I hope your business is fine.
I fixed this issue now, thanks for the bug report 👍  .

Take easy on this project : )
