### ISSUE TITLE
Korean translastion for great WinXShell 

### ISSUE THREAD

**Issue by nonamemanSEO** [slorelee/wimbuilder2#17]
Here is my Korean translation file for your WinXShell.
I know that it's maybe not very important directly in this wimbuilder project, 
but i want to support your another great work - WinXShell :)
I hope that my Korean translation would be included in the next release. 

[WinXShell_4_Wimbuilder_KOR_20190615.zip](https://github.com/slorelee/wimbuilder2/files/3292844/WinXShell_4_Wimbuilder_KOR_20190615.zip)

**Comment by slorelee** [comment]
Thanks for that. I will add them in next release.
I also change some TEXT with system dll resource, make sure it
can show in locale language strings than English.

Close as it is not about the WimBuilder project.
