### ISSUE TITLE
release 2019 06 21 full has not include SIB, PEnetwork, 7zip. and Does not show full index in install.wim

### ISSUE THREAD

**Issue by apple3000** [slorelee/wimbuilder2#18]
hi, in https://github.com/slorelee/wimbuilder2/releases
packaged with PECMD, WinXShell, StartIsBack, 7-Zip, PENetwork, HotSwap
1. But, "2019 06 21 full" asset has not include SIB, PEnetwork, 7zip.

2. It Does not show full index in install.wim. my install.wim has over 10 index. but it just shows 6.

3. Another one, 
in Your Builder, How to save my setiings ?
I checked some modules to build. close the builder. And After restarting the builder, my check box was initialized.

**Comment by slorelee** [comment]
1. those applications moved to \vendor folder. with the Official download file format.

They will be easy to update later by me, or userself.

and I will seperate others (PECMD, WinXShell) to vendor. so user can download wimbuilder2-master.zip,
then copy the vendor to it, to get the lastest develop version.

**Comment by slorelee** [comment]
> 2.It Does not show full index in install.wim. my install.wim has over 10 index. but it just shows 6.

The lastest version makes the list to be 99.

download and replace the hta file:
https://raw.githubusercontent.com/slorelee/wimbuilder2/master/WimBuilder_UI.hta

or just modify:
https://github.com/slorelee/wimbuilder2/commit/09ba4ec352c38ba383f861a159813bba5dce94de#diff-9bf4bae1e18dc45162f5d1d1e939a821

**Comment by slorelee** [comment]
> Another one, in Your Builder, How to save my setiings ?

move to #19, because I have plan on it.

if 1. and 2.  are OK, Could you close this issue?

**Comment by apple3000** [comment]
very thanks.  today i added apps(sib 7zip penetwork) to script folder from official sites. good working!.
and good saving method !. i wish you will successfully add to next version.

index problem solved as your mention.

**Comment by slorelee** [comment]
Note: **7z1900.exe** needs be rename to **7z1900-x86.exe** for building x86 PE.

I will add a README.txt file in next version.

**Comment by slorelee** [comment]
> i wish you will successfully add to next version.

They already in **WimBuilder2-Full.7z**.

Those applications moved to **WimBuilder22-Full\\vendor** folder with the Official download file format.
