### ISSUE TITLE
How to save my setiings?

### ISSUE THREAD

**Issue by slorelee** [slorelee/wimbuilder2#19]
@apple3000 #18 
I checked some modules to build. close the builder. And After restarting the builder, my check box was initialized.

**Comment by slorelee** [comment]
Yes, for now, the [save settings as...] feature is not implemented. I planed to do it.
but you can use the next way for the initializing.

**Comment by slorelee** [comment]
Use **Preset** to initialize the custom settings than default settings.

1. copy _assets_\defaut.js to be _assets_\custom.js
2.a. open custom.js and modify the options in **_$patches_opt_**.
   (You can know the option names in Build page)

2.b. open custom.js and modify the **_patches_state_init()_** function to
   select/deselect/open the patch tree nodes.

**Comment by slorelee** [comment]
v2019.12.12 and later releases can save the settings to 'current' preset.

**Comment by apple3000** [comment]
very thanks.

2020년 1월 20일 (월) 오후 10:13, slore <notifications@github.com>님이 작성:
