### ISSUE TITLE
[Question] WES FBWF Size

### ISSUE THREAD

**Issue by BiatuAutMiahn** [slorelee/wimbuilder2#23]
How can I customize FBWF.cfg size? 1024, 2048?

**Comment by slorelee** [comment]
There is the option for this already.

[fbwf_settings.png]()

**Comment by BiatuAutMiahn** [comment]
I refer specifically to FBWF.cfg
![image](https://user-images.githubusercontent.com/6149596/76208388-f3892080-61d5-11ea-9be5-f30594a9ea18.png)

**Comment by slorelee** [comment]
`reg add HKLM\Tmp_System\ControlSet001\Services\FBWF /v WinPECacheThreshold /t REG_DWORD /d %_fbwf_size% /f`

The registry can support to 4095MB(4GB)   size, it is better use the origin fbwf.sys without the fbwf.cfg. so there is not fbwf_1024.cfg, fbwf_2048.cfg.

If you really want to use the low fbwf size with WES's fbwf.sys driver, you needs to modify the fbwf.cfg by yourself, or use the files which is modified by others.
If you diff the *.cfg files, you will see two diff offsets. One is the cache size long integer in hex binary bytes, One is the checksum of the file, when you modify the cache size in hex binary bytes, you need update the checksum of the file.

**Comment by slorelee** [comment]
The attachment with next files:

- 256.cfg
- 512.cfg
- 1024.cfg
- 2048.cfg
- 3072.cfg
- 4096.cfg
- 6144.cfg
- 8192.cfg
- 10240.cfg
- 12288.cfg

[fbwf.zip](https://github.com/slorelee/wimbuilder2/files/4306418/fbwf.zip)

**Comment by BiatuAutMiahn** [comment]
cool, thank you
