### ISSUE TITLE
invalid procedure call or argument

### ISSUE THREAD

**Issue by Lukiya** [slorelee/wimbuilder2#25]
构建时报错: "invalid procedure call or argument"
修改 assets/htakit/js/lib/fso.js 71行
var objFile = fso.CreateTextFile(filename, true)
改为
var objFile = fso.CreateTextFile(filename, true, true)
后问题解决

**Comment by slorelee** [comment]
感谢反馈。
你是在非简体中文环境下使用，且WimBuilder2的语言设置的是zh-CN对吧。

有个资源信息是简体中文所以导致非简体中文环境写入文件失败，
这个文件不能采用Unicode编码，所以不能修改上面的库函数。

这个地方修改的话，所有写文件都会受到影响，内容是不正确的。

**Comment by Lukiya** [comment]
确实是，语言改选Auto后问题解决，谢谢。
另外个问题，我的ISO是英文版的，打开中文软件，文字全部变成了问号，这个有办法在WimBuilder里怎么设置一下成支持中文显示么？

**Comment by slorelee** [comment]
>https://github.com/slorelee/wimbuilder2/blob/9f4f215be016db38457ebed8a2b6dce22386345f/Projects/WIN10XPE/02-PEMaterial/zh-CN.js

你更新这个文件的话，中文语言也可以正常了。
加了语言判断，如果制作环境不是zh-CN的话，使用英文的信息。

**Comment by Matthew-Wai** [comment]
> 另外个问题，我的ISO是英文版的，打开中文软件，文字全部变成了问号

Do you mean you have created an English version of Win10XPE from an English version of Windows ISO file?

**Comment by Lukiya** [comment]
> > 另外个问题，我的ISO是英文版的，打开中文软件，文字全部变成了问号
> 
> Do you mean you have created an English version of Win10XPE from an English version of Windows ISO file?

是的，在正常Windows里，只需要去设置的Region里把System Local改成中文就好了，但是定制PE的时候不知道怎么做这一步。

**Comment by Matthew-Wai** [comment]
> 是的，在正常Windows里，只需要去设置的Region里把System Local改成中文就好了，但是定制PE的时候不知道怎么做这一步。

Moreover, Chinese file names cannot be displayed on File Explorer even if you have added Chinese fonts into the "**C:\Windows\Fonts**" folder.

**Comment by Matthew-Wai** [comment]
> 加了语言判断，如果制作环境不是zh-CN的话，使用英文的信息。

Lukiya was not referring to 制作环境 of Wim Builder.
Lukiya was referring to an English version of Win10XPE created from an English version of Windows ISO file.
