### ISSUE TITLE
繁體注音輸入法

### ISSUE THREAD

**Issue by billjrm** [slorelee/wimbuilder2#26]
繁體注音輸入法(韓文應該也是這樣)必須在 LoadShell 階段，執行 IME_Cmd.cmd 才能正常運作 (只有 ctfmon.exe 不夠 ) 。

所以必須把 %X_SYS%\pecmd.ini 中這行
IFEX %WinDir%\System32\ctfmon.exe, EXEC PECMD.exe EXEC -su %WinDir%\System32\ctfmon.exe
改成 
EXEC =! IME_Cmd.cmd

pecmd.ini 中這行的寫法很怪
IFEX %WinDir%\System32\ctfmon.exe, EXEC PECMD.exe EXEC -su %WinDir%\System32\ctfmon.exe
因為 pecmd.exe 執行 pecmd.ini 內容，但此處又叫用一次 PECMD.exe EXEC -su 感覺很怪。

另外 IME\IME_Cmd.txt 中，這行也很怪
PECMD.EXE EXEC -su ctfmon.exe
改成
ctfmon.exe 或是 start ctfmon.exe
就可以了

因為 pecmd.exe, pecmd.ini, IME_Cmd.cmd, ctfmon.exe 都在 system32 下，所以我叫用時無指定完整路徑

以下加到 IME\Ime_zh-TW.bat 最後面，繁體注音輸入法就可以正常運作。

rem IME_Cmd.cmd must exec (just ctfmon.exe not enough) for Ime_zh-TW when LoadShell
if "x%PE_LOADER%"=="xLUA" (
    call TextReplace "%X_PEMaterial%\pecmd.lua" "exec('PECMD.EXE EXEC -su ctfmon.exe')" "exec('/hide', 'cmd.exe /c IME_Cmd.cmd')"
)
if "x%PE_LOADER%"=="xPECMD" (
rem try add "EXEC =! IME_Cmd.cmd" but not work,  use EXEC *IME_Cmd.cmd
    call TextReplace "%X_SYS%\pecmd.ini" "IFEX #pWinDir#p\System32\ctfmon.exe, EXEC PECMD.exe EXEC -su #pWinDir#p\System32\ctfmon.exe" "EXEC *IME_Cmd.cmd"
)
rem startnet.cmd is OK

在 pecmd.ini 中，本來想改成 EXEC =! IME_Cmd.cmd，不過 TextReplace 一直不成功，目前使用  EXEC  *IME_Cmd.cmd

**Comment by slorelee** [comment]
感谢告知修复方法。
PECMD的代码不熟，写的不是很好。
ctfmon.exe进程需要以SYSTEM权限启动，至于为什么另外使用PECMD.exe来执行，
不记得，应该是影响了作为Loader的进程，所以改了。

这个月的发布版本，将修复这个问题。

TextReplace有点费事，我还是将IME_Cmd.cmd放置到Startup\BeforeShell中统一执行好了。

**Comment by billjrm** [comment]
以前微軟有篇文章(現在找不到了)，介紹如何將 簡/繁/日/韓 輸入法加入 Win7 PE  中。
Add Input Method Editor (IME) to Windows PE

不過，還好這裡有節錄此部分 (用關鍵字 IME 搜尋此文)
https://www.twblogs.net/a/5b7e2d302b7177683855bdf4

CTFMON.EXE 是用  start CTFMON.EXE 運行 

我目前作法也是如此，且運作正常，不需要 SYSTEM 權限啟動。供你参考‧。

Winbuilder 對中文的支援很差，還會產生 Bug，在下面開發中文 PE， 蠻痛苦的。很高興看到原生支援中文的 PE builder (連繁體竟然也可以，棒)， 加油!!

**Comment by slorelee** [comment]
单纯的start CTFMON.exe输入法是可以用，但是19h1之后的版本，
在PE下无法显示候选字输入框（至少简体中文的输入法是这样的）。

通过调查需要:
* ctfmon.exe以SYSTEM身份运行(Administrator帐户需要-su)
* 处理系统文字服务对PE环境的识别

**Comment by slorelee** [comment]
> https://www.twblogs.net/a/5b7e2d302b7177683855bdf4

这个链接我访问不到，如果方便的话，你可以保存PDF，作为附件上传到这里。

**Comment by slorelee** [comment]
>Winbuilder 對中文的支援很差，有時會因中文產生額外的 Bug，在下面開發中文 PE， 蠻痛苦的。很高興看到原生支援中文的 PE builder (連繁體竟然也可以，棒)， 加油!!

你可以搜索工程下面的 zh-CN.js，对应的创建zh-TW.js的话，
所有界面可以显示繁体中文信息。

内部代码的话，大部分是通用的，极少个别功能与语言有关。
代码是批处理完全的ANSI编码，系统能识别就能制作。

**Comment by billjrm** [comment]
[win7pe.pdf](https://github.com/slorelee/wimbuilder2/files/4586419/win7pe.pdf)
第12頁有談到 Win7 加 IME 的方式。

繁中注音輸入法，應該是從 Win7 小幅修改後，拿到 Win10 使用。
Win10 原版光碟所附的簡中輸入法，都是專門為 Win10 寫的，所以比較沒有奇怪的啟動流程。

目前我對程式還不熟，等熟悉一陣子後，再進行繁中化，這樣翻譯會準確一點。

**Comment by Matthew-Wai** [comment]
> 繁體注音輸入法(韓文應該也是這樣)必須在 LoadShell 階段，執行 IME_Cmd.cmd 才能正常運作 

Does it work if "IME_Cmd.cmd" has been put into the following folder?

**\Projects\WIN10XPE\_CustomFiles_\PEMaterial\Autoruns\**

**Comment by slorelee** [comment]
确认了，其实只要regsvr32 IMETCCore.dll的话，注音输入法就可以用了。
对比注册表确定，只要补充下面的注册表项目就可以用了。

Z:\WimBuilder2\Projects\WIN10XPE\01-Components\IME\Ime_zh-TW.bat

:UDPATE_REGISTY
call RegCopyEx Classes ImeCommonAPIClassFactory1028

目前Shift中/英不可以用，我也不知道使用这个输入法，测试输入
"u"可以输出"一“。

**Comment by billjrm** [comment]
> 测试输入"u"可以输出"一“
這是對的

**Comment by billjrm** [comment]
> 测试输入"u"可以输出"一“

沒錯 
按 u 後，接著按 down arrow ，會出現選字的框框。

**Comment by billjrm** [comment]
> Does it work if "IME_Cmd.cmd" has been put into the following folder?

>\Projects\WIN10XPE_CustomFiles_\PEMaterial\Autoruns\

Sorry, hard to answer your question.
If all other IME files are ready，put IME_Cmd.cmd in autorun can work.
