### ISSUE TITLE
Junk characters again.

### ISSUE THREAD

**Issue by Matthew-Wai** [slorelee/wimbuilder2#27]
I am running an English version of Windows 10. 
Will the following junk characters cause a problem?

![Junk character in a BAT file](https://user-images.githubusercontent.com/51051315/81173792-36e3ed80-8fd3-11ea-99fa-e36cfc1b4a2f.jpg)

**Comment by slorelee** [comment]
It won't cause any problem.
It will be loaded in PE, if the PE is zh-CN language,
other language will display those messages in English.

https://github.com/slorelee/wimbuilder2/blob/master/Projects/WIN10XPE/_CustomFiles_/PEMaterial/locales/zh-CN.lua
