### ISSUE TITLE
[Feature Request] Explorer FTP Support

### ISSUE THREAD

**Issue by BiatuAutMiahn** [slorelee/wimbuilder2#30]
Can you add support for Windows Explorer to mount FTP share using Add Network Location Wizard?

Thank you

**Comment by BiatuAutMiahn** [comment]
Do you have discord?

**Comment by slorelee** [comment]
it was done in master branch 18 days ago, and now FTP support is done in WimBuilder2.v2020.06.06.

**Comment by BiatuAutMiahn** [comment]
tested and confirmed working
