### ISSUE TITLE
[Feature Request]希望新增繁中大易/行列輸入法

### ISSUE THREAD

**Issue by ninja0210** [slorelee/wimbuilder2#31]
您好
繁中PE希望可以新增內建的 大易/行列 輸入法
謝謝

**Comment by slorelee** [comment]
繁体输入法都是别人给我反馈，我添加上的。
我自己不会用。有时间的话，装一个正常的Windows系统，对比下看看。

**Comment by ninja0210** [comment]
繁體Win10是用 %programFiles%\Windows NT\TableTextService\TableTextServiceDaYi.txt 的輸入法
貌似複製txt文件然後註冊表啟用，就可以在PE輸入文字了

**Comment by billjrm** [comment]
[IME_zh-TW.zip](https://github.com/slorelee/wimbuilder2/files/4668679/IME_zh-TW.zip)

大易與行列輸入法，我加進去了
改了  Ime_zh-TW.bat, main.html 兩個檔案
新加入檔案 zh-TW.js

修改過程中，把檔案中 New Phonetic 這個詞，改成 Phonetic (這詞太長，且已經過很久，不新了)，另外Ime_zh-TW.bat 有小些 bug ，我也改過了。

我不方便打簡體字，檔案 zh-CN.js 麻煩你改一下

上傳檔 IME_zh-TW.zip 要改成 IME_zh-TW.7z 後解壓縮

**Comment by ninja0210** [comment]
感謝您

**Comment by billjrm** [comment]
[Ime_zh-TW_v2.zip](https://github.com/slorelee/wimbuilder2/files/4671367/Ime_zh-TW_v2.zip)
做了一點小更動

**Comment by slorelee** [comment]
> [Ime_zh-TW_v2.zip](https://github.com/slorelee/wimbuilder2/files/4671367/Ime_zh-TW_v2.zip)
> 做了一點小更動

我参照你的前一版已经更新了。对比下只是chtDaYi => cht_DaYi,
我已经按照ms_XXX的命名习惯，这样修改了。

感谢你添加了些关于繁体输入法的注释信息。

**Comment by billjrm** [comment]
改程式也是要符合原創的風格，這樣看起來才漂亮。
我只是盡點微薄之力，沒有什麼，能幫到忙，我也很高興。
