### ISSUE TITLE
How to add customized driver?

### ISSUE THREAD

**Issue by Lukiya** [slorelee/wimbuilder2#32]
I tried copy drivers folder to /Projects/WIN10XPE/01-Drivers/10-CustomDrivers, but apparently it doesn't work like this way. Is there any easy way to add custom drivers?

**Comment by slorelee** [comment]
It is empty, not work now.
AFAIK, there are two way to integrate drivers.
a). unload registry hive then use dism /add-drivers command on building.
b). copy drivers to X:\MyDrivers or somewhere, then pnputil or drvload command load drivers on booting.
