### ISSUE TITLE
Unicode encoding :: UTF-8 or UTF-16(w or w/o BOM)

### ISSUE THREAD

**Issue by nonamemanSEO** [slorelee/wimbuilder2#4]
This may not be crucial, but I've run into errors some times when running the WimBuilder.
It depends on what kind of encoding the new file the editor software creates.
If you have a recommended encoding option , let me know.
I use Notepad 3 mainly.
Now It seems to have no error after changing to default setting with UFT-16 LE BOM encoding.

**Comment by slorelee** [comment]
Hi, first the encoding is UTF-8, but it needs ADODB.Stream COM, which is not present in origin winre.wim.

WimBuilder2 can be used in origin winre.wim, so I remove the ADODB dependency,
change all resouces files to  **UTF-16LE BOM**.

_// remove ADODB dependency, i18n resources files' encoding need to be UTF-16LE BOM_

https://github.com/slorelee/wimbuilder2/blob/4b3112783fdd6acda4a0c6c4463d810d15489747/assets/htakit/js/lib/fso.js#L10

**Comment by nonamemanSEO** [comment]
> Hi, first the encoding is UTF-8, but it needs ADODB.Stream COM, which is not present in origin winre.wim.
> 
> WimBuilder2 can be used in origin winre.wim, so I remove the ADODB dependency,
> change all resouces files to **UTF-16LE BOM**.
> 
> _// remove ADODB dependency, i18n resources files' encoding need to be UTF-16LE BOM_
> 
> [wimbuilder2/assets/htakit/js/lib/fso.js](https://github.com/slorelee/wimbuilder2/blob/4b3112783fdd6acda4a0c6c4463d810d15489747/assets/htakit/js/lib/fso.js#L10)
> 
> Line 10 in [4b31127](/slorelee/wimbuilder2/commit/4b3112783fdd6acda4a0c6c4463d810d15489747)
> 
>  // remove ADODB dependency, i18n resources files' encoding need to be UTF-16LE BOM

HaHaHa~ ^ 0 ^
I thought I’d seen it somewhere, but I couldn’t remember.
I will always cheer you on to make your coding perfect.
