### ISSUE TITLE
构建ISO之后无法进入PE

### ISSUE THREAD

**Issue by Pinghigh** [slorelee/wimbuilder2#40]
构建ISO后生成的BOOTPE.iso无法使用
在VMware使用时显示windows启动页面后只有黑屏和光标

**Comment by slorelee** [comment]
请明确说明你使用的ISO版本以及选项。

目前20H1, 20H2, 21H1 以及最新预览版都是正常的，发现部分老的版本初始版本正常，月度更新版本无法正常。

例如，cn_windows_10_business_editions_version_1909_updated_april_2020_x64_dvd_5d3fcf2e.iso 
(18362.778)无法正常进入桌面，cn_windows_10_consumer_editions_version_1909_x64_dvd_76365bf8.iso( 18362.418) 初始版本正常，对于 1909 来说(从18362.720开始无法正常)。

**Comment by Pinghigh** [comment]
> 请明确说明您使用的ISO版本以及选项。
> 
> 目前20H1、20H2、21H1以及最新预览版都是正常的，发现部分老的版本初始版本正常，月度更新版本无法正常。
> 
> 例如，cn_windows_10_business_editions_version_1909_updated_april_2020_x64_dvd_5d3fcf2e.iso
> （**18362.778**）无法正常进入桌面，cn_windows_10_consumer_editions_version_1909_x64_dvd_76365bf8.iso（**18362.418，909**。从

20H2的iso，选项是默认之后外壳换成winXshell

**Comment by slorelee** [comment]
20H2新版本出来一直在测试，方便的话说下具体小版本号，以及ISO名。
另外，WimBuilder2-master仅包含代码，不含第三方工具，如果你选WinXShell外壳是没有启动的。
需要下载Release页面的完整包。

**Comment by Pinghigh** [comment]
> 20H2新版本出来一直有测试，没有发现没有启动的情况，方便的话说下具体小版本号，以及ISO名。
> 另外，WimBuilder2-master仅包含代码，不含第三方工具，如果你选WinXShell外壳是没有启动的。
> 需要下载Release页面的完整包。

文件名“Win10_20H2_v2_Chinese(Simplified)_x64.iso”
还有程序文件夹是“WimBuilder2-Full.v2021-02-02”
我再试试用explorer吧

**Comment by Pinghigh** [comment]
> 20H2新版本出来一直有测试，没有发现没有启动的情况，方便的话说下具体小版本号，以及ISO名。
> 另外，WimBuilder2-master仅包含代码，不含第三方工具，如果你选WinXShell外壳是没有启动的。
> 需要下载Release页面的完整包。

另外日志构建模式和CMD构建模式的效果有差异吗？

**Comment by slorelee** [comment]
> 另外日志构建模式和CMD构建模式的效果有差异吗？

构建没有差异，日志模式会保留下构建的信息(批处理运行过程的输出结果，用于判断对比哪里出了问题)。

CMD构建模式，自己可以在 main.bat/last.bat中添加适当的pause等交互命令，
用于调试。日志模式无法交互，这种会卡住。

**Comment by Pinghigh** [comment]
> > 另外日志构建模式和CMD构建模式的效果有差异吗？
> 
> 构建没有差异，日志模式会保留下构建的信息(批处理运行过程的输出结果，用于判断对比哪里出了问题)。
> 
> CMD构建模式，自己可以在 main.bat/last.bat中添加适当的pause等交互命令，
> 用于调试。日志模式无法交互，这种会卡住。

用日志+Explorer成功启动并进入桌面
请问如何增加应用和系统安装模块？

**Comment by slorelee** [comment]
> 请问如何增加应用和系统安装模块？

对于PE来说，就是往X盘(boot.wim)中添加文件和修改注册表。

应用软件如果是绿色版，直接 放到
`WimBuilder2\Projects\WIN10XPE\X\Program Files\`

如果使用PE外置集 放到
`WimBuilder2\vendor\_PEMaterial_\Program Files\`

就会添加进去。也可以外置到PETools，PEMaterial。方法有很多种，不太好说。

你可以参考 软件 下面的 7-Zip, PENetwork。

系统组件功能，先搞清楚需要补充的系统dll和注册表信息，然后可以写个main.bat 从install.wim 提取文件和注册表。

**Comment by Pinghigh** [comment]
> > 请问如何增加应用和系统安装模块？
> 
> 对于PE来说，就是往X盘(boot.wim)中添加文件和修改注册表。
> 
> 应用软件如果是绿色版，直接 放到
> `WimBuilder2\Projects\WIN10XPE\X\Program Files\`
> 
> 如果使用PE外置集 放到
> `WimBuilder2\vendor\_PEMaterial_\Program Files\`
> 
> 就会添加进去。也可以外置到PETools，PEMaterial。方法有很多种，不太好说。
> 
> 你可以参考 软件 下面的 7-Zip, PENetwork。
> 
> 系统组件功能，先搞清楚需要补充的系统dll和注册表信息，然后可以写个main.bat 从install.wim 提取文件和注册表。

弱弱地问一句，这个可以用来安装系统吗

**Comment by slorelee** [comment]
>弱弱地问一句，这个可以用来安装系统吗

直接执行 系统的 Setup.exe 可以安装原版系统。
另外，外置工具包中有 WinNTSetup，第三方安装工具。
