### ISSUE TITLE
最新版的release 下载后的MD5 对不上

### ISSUE THREAD

**Issue by weiling103** [slorelee/wimbuilder2#43]
最新版的release 下载后的MD5 对不上

**Comment by weiling103** [comment]
文件名: H:\4.OS\PE\WinBuilder2\WimBuilder2-Full.v2021-04-04 (1).7z
文件大小: 65295878 字节 (62.27 MB)
修改日期: 2021-04-23 22:31
MD5: e20a33675ea5d899123f206eb656fcf3
SHA1: 17afe3d0c879f5eb23208eb108b908a879ea1b1c
SHA256: dcbf7f8b6295f6cd0e744c876d3307ec6b88d1e12f9c14542f45f8148c76607c
CRC32: 7b4fe56f

**Comment by slorelee** [comment]
http://bbs.wuyou.net/forum.php?mod=redirect&goto=findpost&ptid=411399&pid=4271655&fromuid=166812

MD5是对的。发布后 UserConfig.cmd 有点问题导致，导致每次都重新覆盖AppData，设定无法保存。
重新打包了一次(WimBuilder2-Full.v2021-04-04.7z)，页面上的的MD5信息漏更新了。
