### ISSUE TITLE
如何替换pe默认的桌面壁纸啊？

### ISSUE THREAD

**Issue by Dimitri2020007** [slorelee/wimbuilder2#45]
<img width="241" alt="捕获" src="https://user-images.githubusercontent.com/72486732/119922357-3cc3bc80-bfa2-11eb-9656-ba1e1d1d5547.PNG">
开机背景的壁纸修改是生效了

<img width="150" alt="捕获1" src="https://user-images.githubusercontent.com/72486732/119922415-55cc6d80-bfa2-11eb-8d69-51acd14d84e2.PNG">
改了这个并没有替换默认的桌面壁纸

怎么替换pe的默认桌面壁纸啊

**Comment by slorelee** [comment]
点击 【壁纸】 下面的图片 可以选择 默认桌面壁纸。

也可以直接替换掉 `WimBuilder2\AppData\_CustomFiles_\wallpaper.jpg` 默认壁纸。

**Comment by Dimitri2020007** [comment]
> 点击 【壁纸】 下面的图片 可以选择 默认桌面壁纸。
> 
> 也可以直接替换掉 `WimBuilder2\AppData\_CustomFiles_\wallpaper.jpg` 默认壁纸。

谢谢，我找到替换位置了
