### ISSUE TITLE
ThinkPad L13和L14开启安全启动后分辨率只有640x480

### ISSUE THREAD

**Issue by ssbty** [slorelee/wimbuilder2#47]
ThinkPad L13和L14开启安全启动后分辨率只有640x480，关闭安全启动则默认1024x768，可选1920x1080。
![IMG_20210623_103020](https://user-images.githubusercontent.com/67818273/123026760-48729980-d40f-11eb-855b-e439baf18885.jpg)
![IMG_20210623_103055](https://user-images.githubusercontent.com/67818273/123026770-4dcfe400-d40f-11eb-9ec7-6303ad2b3bec.jpg)

**Comment by ssbty** [comment]
wimbuilder2版本20210606
win10版本21H1

**Comment by slorelee** [comment]
安全启动的分辨率设定BCD的参数决定的，与生成的BOOT.WIM无关。

**Comment by ssbty** [comment]
> 安全启动的分辨率设定BCD的参数决定的，与生成的BOOT.WIM无关。

谢谢

**Comment by ssbty** [comment]
换成1909版本的BCD，分辨率正常了。

**Comment by ssbty** [comment]
Dev 21354也正常
