### ISSUE TITLE
How can I add webcam and directx into WinPE

### ISSUE THREAD

**Issue by toponehhh** [slorelee/wimbuilder2#53]
Hi Slorelee,

我目前在研究一个项目希望在WINPE下实现live meeting的功能，我发现用的你的工具可以让我在winpe下实现MIC的正常调用，真的是十分感谢！不过我发现摄像头（WebCam）还是无法被正常调用，虽然我尝试去安装它的驱动但是最后总是在设备管理器中显示“缺少相关注册表项，无法驱动该设备”。能不能有劳大师再出一版能使用WebCam的版本，同时最好能集成directx相关组件不然用directshow抓屏还是会有问题，万分感谢！

**Comment by slorelee** [comment]
下次升级时会带一个 摄像头 支持选项。只保证设备可以驱动，摄像头软件可以显示画面。
其他更多功能比如录屏等不保证是否可以正常工作。
