### ISSUE TITLE
无法切换到Administrator用户

### ISSUE THREAD

**Issue by MaxwellSun** [slorelee/wimbuilder2#54]
使用的Win10 1903 X64制作PE， wim使用的Windows 10 Home版本。
工具使用的06-06 Full版本。
定制化页面中构建选择了完整的注册表、64位操作系统支持32位应用程序。启动管理使用的PECMD、账户选择启动Administrator并创建用户配置文件。

PE启动后出现System和Administrator两个用户，选择Administrator，显示Switch to Administrator，停在这里进行不下去了

**Comment by slorelee** [comment]
用户切换需要使用 tsdiscon.exe，这个程序需要 专业版，企业版。
Home版本缺少此文件。

构建的时候有红色提示信息的。你可能没注意。
