### ISSUE TITLE
Add compatibility for Server 2019/2022/ Win11

### ISSUE THREAD

**Issue by ibay613** [slorelee/wimbuilder2#57]
Thank you for a great product, if its possible to add add support for Server 2019/2022/ Win11, that would be great.

**Comment by slorelee** [comment]
https://github.com/slorelee/wimbuilder2/releases

Usse the v2021.08.08 released package with the updates code, It will support for Windows11 10.0.22449.1000.
The Windows server 2022 has been supported since v2021.04.04.
