### ISSUE TITLE
version mark & log time , please

### ISSUE THREAD

**Issue by nonamemanSEO** [slorelee/wimbuilder2#7]
There are often different misunderstandings when exchanging information about error and so on, since there are no criteria for talking with the same version.

And I suggest that the build start time - the completion time (and the elapsed time) will be displayed on the last log screen.

Good luck, cheer up !

**Comment by slorelee** [comment]
I considered that, I have WB_log.cmd in bin folder, but not really add them for every Patch applying.
Only for start and end is OK.

(off_topic: I want remove extract percent information in last_wimbuilder.log ...)

**Comment by slorelee** [comment]
@nonamemanSEO 

version mark & log time is added.

```
WimBuilder - v2019.03.20.972addea
2019-03-20 08:23:36 - Building Start ... 
...
...
...
2019-03-20 08:24:33 - Building completed in 57 seconds. 

```
