### ISSUE TITLE
在exfat分区中运行wimbuilder2，会卡死

### ISSUE THREAD

**Issue by fuhx** [slorelee/wimbuilder2#74]
在exfat分区中运行wimbuilder2，构建执行到这里卡住半小时了，提示按任意键继续，我按了也没反应。
![无标题](https://user-images.githubusercontent.com/53959183/152292563-1cfa27b1-b25e-4b48-81cb-0f1461963e0e.png)
![Uploading 无标题.png…]()

**Comment by fuhx** [comment]
挂载WIM失败，在NTFS分区运行就没问题

**Comment by slorelee** [comment]
如果是非交互模式，直接报错，不执行pause就好了。下次再修改吧。

exfat分区的话，等dism.exe啥时候适配了才能解决吧。
要么，只能用解压WIM方式了，不过这种太慢了，推荐制作时还是选NTFS分区，
最好用内存盘制作(一般功能2GB，功能多了3GB)。
