### ISSUE TITLE
Experimental functions (ultra slim)

### ISSUE THREAD

**Issue by nonamemanSEO** [slorelee/wimbuilder2#8]
Here is an unorganized batch file. 
In 19H1 18323 x64, Wimbuilder typically produces about 530 megabytes of boot.wim, but this batch file can reduce to 408 megabytes, and its result boots normally and works normally. 
I hope you’ll coding, sort and refine the code, and create a new option called experimental (Ultra Slim). 

[last_custom.bat.txt](https://github.com/slorelee/wimbuilder2/files/2817325/last_custom.bat.txt)

**Comment by slorelee** [comment]
>Here is an **unorganized** batch file.

well, so it is not good to add all of them(I saw some dlls are require on my further features).

you may just create **zb-UltraSlim** folder,
put an empty **main.html**(or write some word like: <p>experimental (Ultra Slim)</p>),
then rename the last_custom.bat  => last.bat

It will work for you as a standalone patch, make it easier to merge with latest version(just copy the folder to WIN10XPE project).

About the 19H1 part, do use test with my settings? I didn't add so much files in it.
What features work with you last_custom.bat then mine?

**Comment by nonamemanSEO** [comment]
solved , thus close
