### ISSUE TITLE
22000.x_amd64_zh-tw_professional_製作繁體PE，VirtualBox測試開機黑屏

### ISSUE THREAD

**Issue by candy999** [slorelee/wimbuilder2#82]
使用UUP建立的22000.xxx zh-tw版本
測試以下兩個版本
22000.194_amd64_zh-tw_professional_dddc80c8_convert_virtual
22000.493_amd64_zh-tw_professional_dc595068_convert_virtual
能正常看到windows logo轉圈讀取，讀取完後就淡出變成黑屏，不會進入桌面。
win10最後的預覽版21390.2025_amd64_zh-tw與server版的20348.558_amd64_zh-tw皆可正常進入桌面環境。
是否win11繁體PE有建立的bug?

**Comment by slorelee** [comment]
我从微软官方直接下载Windows 11测试了下，默认预设可以进入系统不黑屏。

https://www.microsoft.com/zh-cn/software-download/windows11
win11_chinese(traditional)_x64v1.iso

winre.wim[1]: Windows 11 專業教育版 (10.0.22000.318,x64,zh-TW) 

Windows11的繁體PE构建，目前来看和简体中文没有什么区别。

>讀取完後就淡出變成黑屏，不會進入桌面。

是否有鼠标指针？ 有的话，可以CTRL+ALT+DEL调出任务管理器试试。
如果可以的话，那么就是Explorer.exe的问题。

**Comment by slorelee** [comment]
构建支持已官方ISO为主。微软的ISO镜像可以制作繁体PE，暂时认为是uup镜像的问题。
