### ISSUE TITLE
按F11全屏状态下任务栏无法隐藏

### ISSUE THREAD

**Issue by loonpn** [slorelee/wimbuilder2#83]
复现：
  打开资源管理器窗口，按下f11键全屏，任务栏遮挡窗口内容
开始菜单软件：
  startisback
系统版本：Win10 19042以上、win11

事实上不只是资源管理器，几乎所有软件都有这个问题。

**Comment by slorelee** [comment]
这个是 Windows PE下Explorer的功能缺陷，不用额外处理基本都有问题。

需要全屏隐藏时，可以通过 右键 个性化， 或者 任务栏设置 ，把 任务栏改成 自动隐藏 。
