### ISSUE TITLE
mtpHelper_22000_x64.sys 文件报毒

### ISSUE THREAD

**Issue by RagueI** [slorelee/wimbuilder2#86]
![Snipaste_2022-08-13_18-25-59](https://user-images.githubusercontent.com/82907020/184479685-3a0e96a5-5c2d-4227-8493-01dbf8e60ac1.png)

**Comment by slorelee** [comment]
Release包中的mtpHelper驱动签名过期了。 github/gitee上最新更新是新的签名的文件，应该不会提示木马病毒。

如果你不使用MTP（通过USB与手机互传文件）功能的话，可以删除掉这个文件，不影响PE制作。

**Comment by RagueI** [comment]
感谢
