### ISSUE TITLE
Windows 11 22h2 PE 制作完成后没有声音

### ISSUE THREAD

**Issue by KillerJmc** [slorelee/wimbuilder2#91]
ISO版本：Windows 11 22h2
Wimbuilder版本：2022.2 updated
制作完成后在真机测试没有声音。但是控制面板麦克风和扬声器都显示正常。
更奇怪的是如果换成21h2，没改任何设置制作就有声音。

**Comment by slorelee** [comment]
22h2需要登录Admin用户启动声音服务，才有声音。
单独System用户启动的话，需要修改系统的AudioPolicyManager.dll文件。这个修改目前不同版本字节码位置不同，暂时没有更新到W2上。

**Comment by KillerJmc** [comment]
@slorelee 作者大大，那 `AudioPolicyManager.dll` 有计划更新吗？

**Comment by KillerJmc** [comment]
@slorelee 这么做是不是因为System的权限不够，不能加载haudio.inf？
如果是的话有没有不切换用户把声音问题解决的方法？
然后作者大大 `AudioPolicyManager.dll` 有计划更新吗？

**Comment by rradjab** [comment]
Hello, thanks for raising this issue. Please tell me what actions (even temporary ones) are needed to get around this problem?
