### ISSUE TITLE
用同版本fwbf，配置FBWF缓存到120G，制作出来的PE， “X:\”盘只有495M

### ISSUE THREAD

**Issue by smzhzy** [slorelee/wimbuilder2#97]
ISO版本：Windows 11 22h2（22621.2215）
Wimbuilder版本：最新（github）

我用同版本fwbf，并配置FBWF缓存到120G，登录到制作出来的PE， “X:\”盘只有495M。配置FBWF缓存到8G正常。

我还尝试制作Windows10(19045)PE，同样也是提取同版本fwbf，但更奇怪的是不管配置多大FBWF缓存，“X:\”盘始终都只有495M。

我碰到的这个问题希望大佬能帮忙解惑。

**Comment by slorelee** [comment]
设置4 GB内存，使用的是同版本的fwbf驱动，22621还正常吧（22621.2134测试还可以4GB）。
25xxx之后，注册表设置的大小就无效了，只有400多MB。
设置 8GB及以上，会使用WES8的fwbf驱动。

**Comment by smzhzy** [comment]
@slorelee 谢谢slorelee大关注和解答！
可不可以就使用同版本fwbf驱动问题做下优化呢？
