### ISSUE TITLE
PENetwork：無法常駐系統(右下工具列無圖示)，且再執行後也無法帶出GUI設定界面。

### ISSUE THREAD

**Issue by NeoqRpoh** [slorelee/wimbuilder2#99]
PENetwork：無法常駐系統(右下工具列無圖示)，且再執行後也無法帶出GUI設定界面。
Wimbuilder2版本：v2023-10-10_TechnologyPreview_lite_preset
OS版本：Win10_X64_22H2_updated_Oct_2023_Cht

但是一樣的環境設置；用舊版的OS製成的PE其PENetwork就正常：Win10_X64_21H2_Cht

**Comment by slorelee** [comment]
default 默认 预设，是否正常？如果默认的正常就是 lite带的【精简】dll，对于新版本有些是需要的。
更新版本的Windows的话，也可以试试不用winre.wim，而是使用boot.wim[2](第二卷)来制作看看。

**Comment by NeoqRpoh** [comment]
試驗過後，您所題的兩個方案皆可行，謝謝！
另外，可以請教關於方案二，用boot.wim/2和用winre.wim來制作PE有何差別嗎？
